src/api.jl

This fixes the current broken build and keeps the package compatible with `v0.6` and `v0.7` after the change in expression parsing that puts `Symbol`s in `QuoteNode`s instead of `Expr` objects (JuliaLang/julia#23885).
I also changed a few references to left-hand side (LHS) and right-hand side (RHS) which seemed backwards. Let me know if anything is missing or erroneous.
Thanks!

Allow diff rule function to be in an expression or QuoteNode

---

src/rules.jl

Like the title says, this PR adds derivatives for `Base.transpose` and `Base.\`.

Derivatives for `Base.transpose` and `Base.\`

---

src/rules.jl

Add max, min, and abs.

---

src/rules.jl

This is a possible fix for #14.
I don't know if the version being used here is correct.  I *do* know that on the first 0.7 release candidate, making this definition was giving a method overwrite error.  I'd be happy to change if anyone knows what the proper condition for this definition is, or where I might be able to find that.

fixed method overwrite of `log1p`

---

src/rules.jl
test/runtests.jl

Fixes #17.
Lines were broken because they became too long.

Qualify special functions with module name.

---

src/rules.jl
test/runtests.jl

A couple of symbols weren't interpolated properly in a couple of the definitions. This fixes them and changes the unit testing slightly to use less-likely-to-be-chosen symbols for variable names.

Fix interpolation

---

src/rules.jl

The intention here is to allow CSE to re-use the value it computed on the forward pass.

Compute tanh derivative as 1 - tanh(x)^2

---

src/rules.jl

This is the kind of hack that is obsoleted by ChainRules' method overloading approach vs a symbolic table, but in the meantime, this will enable @dpsanders to define an `abs` derivative for Intervals

add hook for abs definition that downstream packages can overload

---

Project.toml
src/rules.jl

In version 0.8 of `SpecialFunctions` `lgamma` was split into `loggamma` and `logabsgamma` where the latter returns a tuple of the value and the sign. Similarly changes were made for `lbeta`. The old `lgamma` and `lbeta` used to return just the log of the absolute value of the argument which often was forgotten. That was also the case for the definitions here in `DiffRules` but luckily that means that the definitions become correct when we change `lgamma` to `loggamma` and `lbeta` to `logbeta` as this PR does. I plan to release version 0.1 once this PR has been merged since there are downstream packages waiting for this.

Upgrade to SpecialFunctions 0.8

---

src/rules.jl

This solves a common issue where taking the derivative of f(x::Float32, y::Int) = x / y with respect to x accidentally promotes the number type from Float32 to Float64.
This issue is rather unexpected and hard to discover in Flux.
Ref:
- https://github.com/FluxML/Flux.jl/issues/815
- https://github.com/FluxML/Flux.jl/issues/1026
- https://github.com/JuliaDiff/DiffRules.jl/issues/26

Avoid inv() in / and \

---

Project.toml
src/rules.jl
test/runtests.jl

Closes #47, closes #28.
And closes #32 now.

Add `ifelse` & `muladd` rules

---

Project.toml
src/rules.jl
test/runtests.jl

This removes the 3-argument rules introduced in https://github.com/JuliaDiff/DiffRules.jl/pull/54
While they appear to be explicitly supported by this package, they are violently rejected by ForwardDiff, it turns out. 
According to https://github.com/SciML/ColPrac#accidental-breaking-releases the right path is to immediately tag a patch version without the problematic changes.

Comment out trinary rules

---

.github/workflows/downstream.yml

This should add a CI run which tests ForwardDiff. Based on https://github.com/SciML/DiffEqBase.jl/blob/master/.github/workflows/Downstream.yml
Possibly other packages should be included. There's a list here: https://juliahub.com/ui/Packages/DiffRules/x2ZNk/1.2.1?t=2
I added a few. If I couldn't find the tests, or the took over an hour to run, or they seemed to be failing already, then I skipped the package. (Nabla somehow got in despite failing here: https://github.com/invenia/Nabla.jl/runs/2981519710?check_suite_focus=true, same message a few days ago so not caused by latest DiffRules PRs.)

Add integration tests

---

src/rules.jl

This one causes quite a lot of invalidations (https://github.com/SciML/DiffEqBase.jl/pull/698#issuecomment-896872594). It was added in https://github.com/JuliaDiff/DiffRules.jl/pull/54 but it is unclear why it was added.
Is it needed for anything?

remove rule for identity

---

.github/workflows/downstream.yml
Project.toml
src/rules.jl

This PR removes the rules for `conj`, `adjoint`, and `transpose` since they cause problems with ReverseDiff (https://github.com/JuliaDiff/DiffRules.jl/pull/54 broke some tests for `adjoint`; see https://github.com/JuliaDiff/ReverseDiff.jl/issues/183#issuecomment-921287528 and the other comments there for details) and the default fallbacks in https://github.com/JuliaLang/julia/blob/c5f348726cebbe55e169d4d62225c2b1e587f497/base/number.jl#L211-L213 should be sufficient (similar to the discussion about `identity` in https://github.com/JuliaDiff/DiffRules.jl/pull/64).
I checked locally that the ReverseDiff issues are fixed by this PR.
**Edit**: I also added ReverseDiff to the integration tests.

Remove rules for `conj`, `adjoint`, and `transpose`

---

.github/workflows/CompatHelper.yml
.github/workflows/DocsPreviewCleanup.yml
.github/workflows/TagBot.yml
.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/downstream.yml
docs/make.jl

This PR updates the GH actions and enables a preview of the documentation.
Probably most importantly, I added the "cancel actions for old commits" feature since otherwise GH actions would be blocked by the longer running integration tests.
These changes are extracted from https://github.com/JuliaDiff/DiffRules.jl/pull/69.

Update GH actions and add preview for docs

---

src/api.jl

The order in which DiffRules.diffrules() outputs things is not deterministic (because it depends on the order in which `keys(..)` returns things).
This means this jldoctest can fail:
```julia
julia> first(DiffRules.diffrules())
(:Base, :log2, 1)
```
Here we make it so that the output is deterministic.

Fix doctest failure

---

Project.toml
src/DiffRules.jl
src/rules.jl

Until recently this package had no dependencies at all. It defines rules for SpecialFunctions and bounds the version needed, but does not load the package. I see no reason that the same mechanism can't be used for LogExpFunctions.
I didn't notice this in #69, and I see no discussion of this change there, everyone was focused on other issues. I think that moving away from zero deps is something that we need a positive reason to do. Until we have one, keeping the old behaviour seems preferable. 
Test failures for 1.7 aren't new, or are new only in that 1.7 is the new 1, not caused by this PR:
```
100
check rules: Test Failed at /home/runner/work/DiffRules.jl/DiffRules.jl/test/runtests.jl:54
101
Expression: isapprox(dy, finitediff((z->begin
102
Base.mod(foo, z)
103
end), bar), rtol = 0.05) …
```

Revert to zero dependencies

---

.github/workflows/ci.yml
Project.toml
src/rules.jl

Increase Julia compat bound to 1.3. This is needed for https://github.com/JuliaDiff/DiffRules.jl/pull/74.
Add CI testing on 1.3 (for consistency with compat) and 1.6 (LTS).

Increase Julia compat 1.3

---

Project.toml
src/rules.jl

This should fix https://github.com/FluxML/Zygote.jl/issues/1132.

AD rule for logerfcx

---

.vscode/settings.json
Project.toml
src/rules.jl
test/runtests.jl

Added a rule for the [function ldexp](https://docs.julialang.org/en/v1/base/math/#Base.Math.ldexp)

Added ldexp to list of diffrules

---

.github/workflows/downstream.yml

Nabla is fully over on ChainRules.
It doesn't use DiffRules anymore

Remove Nabla from downstream tests

---

Project.toml
src/rules.jl
test/runtests.jl

It is unclear to me how the tests work here. I did not find the tests of corner cases.

Add `iszero(x)` branches to `xlogy` and `xlog1py`

---

src/rules.jl

This pull request ensures that the input type is preserved for various rules. 
Previously there were potentially a few places where 64 bit NaN's would always be produced
regardless of the input. To fix this I replaced any instance of `:NaN` with `oftype($x, NaN)`.
Additionally, this pull-request fixes the issue with the `ldexp` rule from #88 which is similar in nature.

Preserve input types for various rules

---

Project.toml
src/rules.jl

Fixes https://github.com/JuliaDiff/ForwardDiff.jl/issues/603 and makes the definitions here consistent with ChainRules (https://github.com/JuliaDiff/ChainRules.jl/blob/5818173b31fac9d358acda21f5751978a5dcb2e5/src/rulesets/Base/fastmath_able.jl#L220).

Use strong zeros in the diffrules for min/max

---

.github/workflows/downstream.yml

The package has had failing CI on releases for quite some time.

Remove EAGO from downstream CI testing

---

src/rules.jl

This PR updates the diffrule for `abs` to return 0 at the non-differentiable point. The current implementation returns 1. Although valid, this can prevent convergence in gradient descent. The implementation in this PR is the behavior the  [ChainRules.jl docs](https://juliadiff.org/ChainRulesCore.jl/dev/maths/nondiff_points.html) advises. 
This also comes with the added benefit of not requiring the type to support the ternary operator such as `IntervalArithmetic.Interval`. This is the use case that led me to make this PR.
```julia
using IntervalArithmetic, ForwardDiff
ForwardDiff.derivative(abs, -2.0 .. 2.0)
```
```julia
ERROR: TypeError: non-boolean (Interval{Float64}) used in boolean context
Stacktrace:
[1] _abs_deriv(x::Interval{Float64})
@ DiffRules …
```

Update abs diff rule to 0 at non-differentiable point

---

Project.toml
src/rules.jl

General form:
$$ \frac{d}{dx} E_\nu(x) = -E_{\nu - 1}(x) $$
Note that:
$$ E_0(x) = \frac{e^{-x}}{x} $$
Therefore, derivative of `SpecialFunctions.expint(x)` ($` E_1(x) `$) is:
$$ \frac{d}{dx} E_1(x) = -E_0(x) = -\frac{e^{-x}}{x} $$
Source: [Wikipedia](https://en.wikipedia.org/wiki/Exponential_integral#Derivatives)

Derivative of exponential integral
